version: '3.9'
services:
    nginx:
        build:
            context: bin/nginx
        container_name: ${CONTAINER_NAME}nginx
        ports:
            - ${PORT_NGINX}:80
            # - ${PORT_NGINX_SSL}:443
        volumes:
            - ./www/${PROJECT}:/usr/share/nginx/html
            - ./config/nginx/default.conf:/etc/nginx/conf.d/default.conf
            - ./logs/nginx/error.log:/var/log/nginx/error.log
            - ./logs/nginx/access.log:/var/log/nginx/access.log
        restart: always
    php:
        build:
            context: bin/php
        container_name: ${CONTAINER_NAME}php
        volumes:
            - ./www/${PROJECT}:/usr/share/nginx/html
            - ./config/php/php.ini:/usr/local/etc/php/php.ini
        restart: always
    redis:
        build:
            context: bin/redis
        container_name: ${CONTAINER_NAME}redis
        depends_on:
            - php
        restart: always
    mysql:
        build:
            context: bin/mysql
        container_name: ${CONTAINER_NAME}mysql
        command: --default-authentication-plugin=mysql_native_password
        ports:
            - ${PORT_MYSQL}:3306
        volumes:
            - ./data/mysql:/var/lib/mysql
            - ./logs/mysql:/var/log/mysql
        environment:
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
            MYSQL_DATABASE: ${MYSQL_DATABASE}
        restart: always